-- =============================================================================
-- MI TRÁMITE BOLIVIA
-- Esquema de referencia + datos de desarrollo (modelo v2)
-- PostgreSQL 16 + pgvector
--
-- ADVERTENCIA:
--   Este archivo es un RESET DE DESARROLLO. Elimina las tablas v1 y v2.
--   No debe ejecutarse sobre producción. Para producción se deben crear
--   migraciones versionadas (por ejemplo, con golang-migrate o Goose).
--
-- PRINCIPIOS DEL MODELO:
--   1. Un trámite no contiene dirección, horario ni costo como texto libre.
--   2. Lo publicado es una versión editorial aprobada e inmutable.
--   3. Toda afirmación publicada puede vincularse con una fuente oficial.
--   4. El scraping crea candidatos; nunca publica automáticamente.
--   5. Los embeddings pertenecen a fragmentos de una versión, no al trámite.
--   6. No se almacenan identificadores de dispositivo en texto claro.
-- =============================================================================

BEGIN;

SET client_encoding = 'UTF8';
SET TIME ZONE 'America/La_Paz';
-- Neon normalmente instala las extensiones en "public". También se incluye
-- "extensions" para conservar portabilidad con otros PostgreSQL administrados.
SET search_path TO public, extensions, pg_catalog;

CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Normalización inmutable e independiente del esquema donde el proveedor
-- instale extensiones. Cubre los diacríticos usados habitualmente en español.
CREATE OR REPLACE FUNCTION public.normalizar_busqueda(valor TEXT)
RETURNS TEXT
LANGUAGE SQL
IMMUTABLE
PARALLEL SAFE
SET search_path TO public, extensions, pg_catalog
AS $$
    SELECT translate(
        lower(coalesce(valor, '')),
        'áéíóúüñ',
        'aeiouun'
    );
$$;

-- -----------------------------------------------------------------------------
-- RESET EXPLÍCITO
-- -----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_tramite_publicado CASCADE;
DROP VIEW IF EXISTS vw_oficina_horario CASCADE;

DROP TABLE IF EXISTS
    feedback_respuesta,
    reporte_ciudadano,
    cita_rag,
    recuperacion_rag,
    mensaje_conversacion,
    conversacion,
    sesion_anonima,
    trabajo_embedding,
    fragmento_conocimiento,
    candidato_ingesta,
    ejecucion_ingesta,
    fuente_ingesta,
    evento_auditoria,
    usuario_rol,
    rol,
    sesion_admin,
    usuario_admin,
    tramite_etiqueta,
    etiqueta,
    resultado_tramite,
    costo_tramite,
    paso_tramite,
    requisito_tramite,
    tramite_oficina,
    modalidad_tramite,
    tramite_version_fuente,
    fuente_oficial,
    tramite_version,
    tramite_alias,
    tramite,
    categoria,
    excepcion_atencion,
    horario_oficina,
    oficina_contacto,
    oficina,
    institucion_alias,
    institucion,
    archivo_multimedia,
    municipio,
    departamento,
    scraping_log,
    fuente_scraping,
    historial_chat,
    tramite_embedding,
    administrador
CASCADE;

-- -----------------------------------------------------------------------------
-- CATÁLOGOS TERRITORIALES
-- -----------------------------------------------------------------------------
CREATE TABLE departamento (
    id              SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(3) NOT NULL UNIQUE,
    nombre          VARCHAR(60) NOT NULL UNIQUE,
    activo          BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE municipio (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    departamento_id SMALLINT NOT NULL REFERENCES departamento(id),
    codigo_ine      VARCHAR(10),
    nombre          VARCHAR(100) NOT NULL,
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (departamento_id, nombre)
);

CREATE UNIQUE INDEX uq_municipio_codigo_ine
    ON municipio(codigo_ine)
    WHERE codigo_ine IS NOT NULL;

-- -----------------------------------------------------------------------------
-- ARCHIVOS MULTIMEDIA
-- Neon conserva metadatos; los binarios viven en object storage externo.
-- Una variante apunta al archivo original mediante original_id.
-- -----------------------------------------------------------------------------
CREATE TABLE archivo_multimedia (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    original_id         UUID REFERENCES archivo_multimedia(id) ON DELETE CASCADE,
    variante            VARCHAR(30) NOT NULL DEFAULT 'original'
                        CHECK (variante IN ('original', 'miniatura', 'pequena',
                                            'mediana', 'grande')),
    proveedor           VARCHAR(30) NOT NULL
                        CHECK (proveedor IN ('s3', 'r2', 'cloudinary', 'otro')),
    contenedor          VARCHAR(120) NOT NULL,
    clave_objeto        TEXT NOT NULL,
    url_publica         TEXT,
    mime_type           VARCHAR(80) NOT NULL
                        CHECK (mime_type IN ('image/svg+xml', 'image/png',
                                             'image/jpeg', 'image/webp')),
    tamano_bytes        BIGINT NOT NULL CHECK (tamano_bytes > 0),
    ancho_px            INTEGER CHECK (ancho_px > 0),
    alto_px             INTEGER CHECK (alto_px > 0),
    sha256              CHAR(64) NOT NULL,
    texto_alternativo   VARCHAR(250) NOT NULL,
    estado              VARCHAR(20) NOT NULL DEFAULT 'pendiente'
                        CHECK (estado IN ('pendiente', 'activo', 'rechazado',
                                          'eliminado')),
    creado_por          BIGINT,
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (proveedor, contenedor, clave_objeto),
    CHECK (
        (variante = 'original' AND original_id IS NULL)
        OR (variante <> 'original' AND original_id IS NOT NULL)
    ),
    CHECK (
        (ancho_px IS NULL AND alto_px IS NULL)
        OR (ancho_px IS NOT NULL AND alto_px IS NOT NULL)
    ),
    CHECK (sha256 ~ '^[0-9a-f]{64}$')
);

CREATE UNIQUE INDEX uq_archivo_variante
    ON archivo_multimedia(original_id, variante)
    WHERE original_id IS NOT NULL;

-- -----------------------------------------------------------------------------
-- INSTITUCIONES Y PUNTOS DE ATENCIÓN
-- -----------------------------------------------------------------------------
CREATE TABLE institucion (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR(40) NOT NULL UNIQUE,
    nombre              VARCHAR(180) NOT NULL,
    sigla               VARCHAR(40) NOT NULL,
    tipo                VARCHAR(30) NOT NULL DEFAULT 'publica'
                        CHECK (tipo IN ('publica', 'privada_delegada', 'mixta')),
    institucion_padre_id BIGINT REFERENCES institucion(id),
    sitio_web           TEXT,
    telefono_general    VARCHAR(80),
    correo_general      VARCHAR(160),
    logo_archivo_id     UUID REFERENCES archivo_multimedia(id),
    estado              VARCHAR(20) NOT NULL DEFAULT 'activa'
                        CHECK (estado IN ('activa', 'inactiva', 'reemplazada')),
    reemplazada_por_id  BIGINT REFERENCES institucion(id),
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (sigla)
);

CREATE TABLE institucion_alias (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id  BIGINT NOT NULL REFERENCES institucion(id) ON DELETE CASCADE,
    alias           VARCHAR(160) NOT NULL,
    normalizado     VARCHAR(160) GENERATED ALWAYS AS
                    (public.normalizar_busqueda(alias)) STORED,
    UNIQUE (institucion_id, normalizado)
);

CREATE TABLE oficina (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id      BIGINT NOT NULL REFERENCES institucion(id),
    municipio_id        BIGINT REFERENCES municipio(id),
    codigo              VARCHAR(60) NOT NULL,
    nombre              VARCHAR(180) NOT NULL,
    tipo                VARCHAR(30) NOT NULL DEFAULT 'oficina'
                        CHECK (tipo IN ('oficina', 'ventanilla', 'brigada_movil',
                                        'punto_pago', 'virtual')),
    direccion           TEXT,
    referencia          TEXT,
    latitud             NUMERIC(9,6) CHECK (latitud BETWEEN -90 AND 90),
    longitud            NUMERIC(9,6) CHECK (longitud BETWEEN -180 AND 180),
    zona_horaria        VARCHAR(50) NOT NULL DEFAULT 'America/La_Paz',
    accesible           BOOLEAN,
    requiere_cita       BOOLEAN NOT NULL DEFAULT FALSE,
    url_cita            TEXT,
    estado              VARCHAR(20) NOT NULL DEFAULT 'activa'
                        CHECK (estado IN ('activa', 'temporal', 'inactiva')),
    verificado_en       TIMESTAMPTZ,
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (institucion_id, codigo)
);

CREATE TABLE oficina_contacto (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oficina_id      BIGINT NOT NULL REFERENCES oficina(id) ON DELETE CASCADE,
    tipo            VARCHAR(20) NOT NULL
                    CHECK (tipo IN ('telefono', 'whatsapp', 'correo', 'web')),
    valor           VARCHAR(200) NOT NULL,
    etiqueta        VARCHAR(80),
    es_principal    BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE horario_oficina (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oficina_id      BIGINT NOT NULL REFERENCES oficina(id) ON DELETE CASCADE,
    dia_semana      SMALLINT NOT NULL CHECK (dia_semana BETWEEN 1 AND 7),
    hora_apertura   TIME NOT NULL,
    hora_cierre     TIME NOT NULL,
    con_cita        BOOLEAN NOT NULL DEFAULT FALSE,
    valido_desde    DATE,
    valido_hasta    DATE,
    CHECK (hora_cierre > hora_apertura),
    CHECK (valido_hasta IS NULL OR valido_desde IS NULL OR valido_hasta >= valido_desde)
);

CREATE TABLE excepcion_atencion (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oficina_id      BIGINT NOT NULL REFERENCES oficina(id) ON DELETE CASCADE,
    fecha           DATE NOT NULL,
    cerrada         BOOLEAN NOT NULL DEFAULT TRUE,
    hora_apertura   TIME,
    hora_cierre     TIME,
    motivo          VARCHAR(250),
    UNIQUE (oficina_id, fecha),
    CHECK (cerrada OR (hora_apertura IS NOT NULL AND hora_cierre IS NOT NULL))
);

-- -----------------------------------------------------------------------------
-- CATÁLOGO Y CICLO EDITORIAL DE TRÁMITES
-- -----------------------------------------------------------------------------
CREATE TABLE categoria (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    padre_id        BIGINT REFERENCES categoria(id),
    codigo          VARCHAR(50) NOT NULL UNIQUE,
    nombre          VARCHAR(100) NOT NULL,
    icono           VARCHAR(50),
    orden           SMALLINT NOT NULL DEFAULT 0,
    activa          BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE tramite (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR(60) NOT NULL UNIQUE,
    slug                VARCHAR(180) NOT NULL UNIQUE,
    institucion_id      BIGINT NOT NULL REFERENCES institucion(id),
    categoria_id        BIGINT REFERENCES categoria(id),
    codigo_oficial      VARCHAR(80),
    alcance             VARCHAR(20) NOT NULL DEFAULT 'nacional'
                        CHECK (alcance IN ('nacional', 'departamental', 'municipal')),
    estado              VARCHAR(20) NOT NULL DEFAULT 'activo'
                        CHECK (estado IN ('activo', 'suspendido', 'retirado')),
    reemplaza_tramite_id BIGINT REFERENCES tramite(id),
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uq_tramite_codigo_oficial
    ON tramite(institucion_id, codigo_oficial)
    WHERE codigo_oficial IS NOT NULL;

CREATE TABLE tramite_alias (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tramite_id      BIGINT NOT NULL REFERENCES tramite(id) ON DELETE CASCADE,
    alias           VARCHAR(200) NOT NULL,
    tipo            VARCHAR(20) NOT NULL DEFAULT 'popular'
                    CHECK (tipo IN ('popular', 'sigla', 'anterior', 'error_comun')),
    normalizado     VARCHAR(200) GENERATED ALWAYS AS
                    (public.normalizar_busqueda(alias)) STORED,
    UNIQUE (tramite_id, normalizado)
);

CREATE TABLE tramite_version (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tramite_id              BIGINT NOT NULL REFERENCES tramite(id) ON DELETE CASCADE,
    numero_version          INTEGER NOT NULL CHECK (numero_version > 0),
    estado_editorial        VARCHAR(20) NOT NULL DEFAULT 'borrador'
                            CHECK (estado_editorial IN
                                  ('borrador', 'en_revision', 'publicada',
                                   'rechazada', 'reemplazada')),
    titulo                  VARCHAR(250) NOT NULL,
    resumen                 VARCHAR(700) NOT NULL,
    descripcion             TEXT NOT NULL,
    publico_objetivo        TEXT,
    resultado_esperado      TEXT,
    advertencias            TEXT,
    plazo_texto             VARCHAR(250),
    vigencia_resultado_texto VARCHAR(250),
    requiere_cita           BOOLEAN NOT NULL DEFAULT FALSE,
    url_inicio              TEXT,
    notas_internas          TEXT,
    valido_desde            TIMESTAMPTZ,
    valido_hasta            TIMESTAMPTZ,
    verificado_en           TIMESTAMPTZ,
    proxima_revision_en     TIMESTAMPTZ,
    creado_por              BIGINT,
    revisado_por            BIGINT,
    aprobado_por            BIGINT,
    creado_en               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    publicado_en            TIMESTAMPTZ,
    hash_contenido          VARCHAR(64),
    UNIQUE (tramite_id, numero_version),
    CHECK (valido_hasta IS NULL OR valido_desde IS NULL OR valido_hasta > valido_desde),
    CHECK (estado_editorial <> 'publicada'
           OR (publicado_en IS NOT NULL AND verificado_en IS NOT NULL))
);

-- Solo puede existir una versión publicada y vigente por trámite.
CREATE UNIQUE INDEX uq_tramite_una_version_publicada
    ON tramite_version (tramite_id)
    WHERE estado_editorial = 'publicada' AND valido_hasta IS NULL;

CREATE TABLE fuente_oficial (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id      BIGINT REFERENCES institucion(id),
    tipo                VARCHAR(25) NOT NULL
                        CHECK (tipo IN ('pagina_web', 'pdf', 'norma', 'api',
                                        'comunicado', 'verificacion_directa')),
    titulo              VARCHAR(300) NOT NULL,
    url                 TEXT NOT NULL,
    fecha_documento     DATE,
    autoridad_emisora   VARCHAR(180),
    hash_contenido      VARCHAR(64),
    consultado_en       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    estado              VARCHAR(20) NOT NULL DEFAULT 'vigente'
                        CHECK (estado IN ('vigente', 'por_verificar',
                                          'no_disponible', 'obsoleta')),
    es_oficial          BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (url)
);

CREATE TABLE tramite_version_fuente (
    tramite_version_id  BIGINT NOT NULL REFERENCES tramite_version(id) ON DELETE CASCADE,
    fuente_id           BIGINT NOT NULL REFERENCES fuente_oficial(id),
    uso                 VARCHAR(25) NOT NULL DEFAULT 'principal'
                        CHECK (uso IN ('principal', 'requisitos', 'costos',
                                       'plazos', 'oficinas', 'normativa')),
    observacion         TEXT,
    PRIMARY KEY (tramite_version_id, fuente_id, uso)
);

CREATE TABLE modalidad_tramite (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tramite_version_id  BIGINT NOT NULL REFERENCES tramite_version(id) ON DELETE CASCADE,
    tipo                VARCHAR(20) NOT NULL
                        CHECK (tipo IN ('presencial', 'en_linea', 'mixta',
                                        'correo', 'brigada_movil')),
    nombre              VARCHAR(120) NOT NULL,
    descripcion         TEXT,
    url_inicio          TEXT,
    requiere_cita       BOOLEAN NOT NULL DEFAULT FALSE,
    orden               SMALLINT NOT NULL DEFAULT 0,
    UNIQUE (tramite_version_id, tipo, nombre)
);

CREATE TABLE tramite_oficina (
    modalidad_id        BIGINT NOT NULL REFERENCES modalidad_tramite(id) ON DELETE CASCADE,
    oficina_id          BIGINT NOT NULL REFERENCES oficina(id),
    notas               TEXT,
    PRIMARY KEY (modalidad_id, oficina_id)
);

CREATE TABLE requisito_tramite (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tramite_version_id  BIGINT NOT NULL REFERENCES tramite_version(id) ON DELETE CASCADE,
    modalidad_id        BIGINT REFERENCES modalidad_tramite(id) ON DELETE CASCADE,
    codigo              VARCHAR(50) NOT NULL,
    titulo              VARCHAR(220) NOT NULL,
    descripcion         TEXT,
    obligatorio         BOOLEAN NOT NULL DEFAULT TRUE,
    cantidad_originales SMALLINT NOT NULL DEFAULT 0 CHECK (cantidad_originales >= 0),
    cantidad_copias     SMALLINT NOT NULL DEFAULT 0 CHECK (cantidad_copias >= 0),
    formato             VARCHAR(100),
    vigencia_documento  VARCHAR(180),
    emisor              VARCHAR(180),
    grupo_alternativa   VARCHAR(50),
    aplica_si           JSONB NOT NULL DEFAULT '{}'::jsonb,
    orden               SMALLINT NOT NULL DEFAULT 0,
    CHECK (jsonb_typeof(aplica_si) = 'object')
);

-- Un mismo requisito lógico puede tener una representación distinta por
-- modalidad (por ejemplo, documento PDF en línea y original presencial).
-- Los índices parciales también evitan duplicados en requisitos generales,
-- donde modalidad_id es NULL.
CREATE UNIQUE INDEX uq_requisito_general_codigo
    ON requisito_tramite(tramite_version_id, codigo)
    WHERE modalidad_id IS NULL;

CREATE UNIQUE INDEX uq_requisito_modalidad_codigo
    ON requisito_tramite(tramite_version_id, modalidad_id, codigo)
    WHERE modalidad_id IS NOT NULL;

CREATE TABLE paso_tramite (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tramite_version_id  BIGINT NOT NULL REFERENCES tramite_version(id) ON DELETE CASCADE,
    modalidad_id        BIGINT REFERENCES modalidad_tramite(id) ON DELETE CASCADE,
    numero              SMALLINT NOT NULL CHECK (numero > 0),
    titulo              VARCHAR(220) NOT NULL,
    descripcion         TEXT NOT NULL,
    lugar               VARCHAR(180),
    url_accion          TEXT,
    es_fuera_sistema    BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (tramite_version_id, modalidad_id, numero)
);

CREATE TABLE costo_tramite (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tramite_version_id  BIGINT NOT NULL REFERENCES tramite_version(id) ON DELETE CASCADE,
    modalidad_id        BIGINT REFERENCES modalidad_tramite(id) ON DELETE CASCADE,
    concepto            VARCHAR(180) NOT NULL,
    moneda              CHAR(3) NOT NULL DEFAULT 'BOB',
    monto               NUMERIC(12,2) CHECK (monto >= 0),
    monto_desde         NUMERIC(12,2) CHECK (monto_desde >= 0),
    monto_hasta         NUMERIC(12,2) CHECK (monto_hasta >= 0),
    es_gratuito         BOOLEAN NOT NULL DEFAULT FALSE,
    periodicidad        VARCHAR(50),
    medio_pago          VARCHAR(180),
    instrucciones       TEXT,
    aplica_si           JSONB NOT NULL DEFAULT '{}'::jsonb,
    verificado_en       TIMESTAMPTZ,
    CHECK (jsonb_typeof(aplica_si) = 'object'),
    CHECK (
        es_gratuito
        OR monto IS NOT NULL
        OR (monto_desde IS NOT NULL AND monto_hasta IS NOT NULL)
    ),
    CHECK (monto_hasta IS NULL OR monto_desde IS NULL OR monto_hasta >= monto_desde)
);

CREATE TABLE resultado_tramite (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tramite_version_id  BIGINT NOT NULL REFERENCES tramite_version(id) ON DELETE CASCADE,
    nombre              VARCHAR(220) NOT NULL,
    formato             VARCHAR(80),
    vigencia            VARCHAR(180),
    entrega             VARCHAR(180),
    orden               SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE etiqueta (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            VARCHAR(80) NOT NULL UNIQUE,
    nombre          VARCHAR(100) NOT NULL
);

CREATE TABLE tramite_etiqueta (
    tramite_id      BIGINT NOT NULL REFERENCES tramite(id) ON DELETE CASCADE,
    etiqueta_id     BIGINT NOT NULL REFERENCES etiqueta(id) ON DELETE CASCADE,
    PRIMARY KEY (tramite_id, etiqueta_id)
);

-- -----------------------------------------------------------------------------
-- USUARIOS ADMINISTRATIVOS, ROLES Y AUDITORÍA
-- -----------------------------------------------------------------------------
CREATE TABLE usuario_admin (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo              VARCHAR(180) NOT NULL UNIQUE,
    nombre              VARCHAR(160) NOT NULL,
    password_hash       TEXT,
    proveedor_identidad VARCHAR(30) NOT NULL DEFAULT 'local'
                        CHECK (proveedor_identidad IN ('local', 'oidc', 'externo')),
    sujeto_externo      VARCHAR(200),
    estado              VARCHAR(20) NOT NULL DEFAULT 'pendiente'
                        CHECK (estado IN ('pendiente', 'activo', 'bloqueado', 'revocado')),
    ultimo_acceso_en    TIMESTAMPTZ,
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (proveedor_identidad <> 'local' OR password_hash IS NOT NULL OR estado = 'pendiente')
);

CREATE TABLE sesion_admin (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    usuario_id          BIGINT NOT NULL REFERENCES usuario_admin(id) ON DELETE CASCADE,
    refresh_token_hash  CHAR(64) NOT NULL UNIQUE,
    ip_hash             CHAR(64),
    user_agent          VARCHAR(300),
    expira_en           TIMESTAMPTZ NOT NULL,
    revocada_en         TIMESTAMPTZ,
    creada_en           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ultimo_uso_en       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (expira_en > creada_en)
);

CREATE TABLE rol (
    id              SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(40) NOT NULL UNIQUE,
    nombre          VARCHAR(100) NOT NULL,
    permisos        JSONB NOT NULL DEFAULT '[]'::jsonb,
    CHECK (jsonb_typeof(permisos) = 'array')
);

CREATE TABLE usuario_rol (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      BIGINT NOT NULL REFERENCES usuario_admin(id) ON DELETE CASCADE,
    rol_id          SMALLINT NOT NULL REFERENCES rol(id) ON DELETE CASCADE,
    institucion_id  BIGINT REFERENCES institucion(id),
    asignado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uq_usuario_rol_global
    ON usuario_rol(usuario_id, rol_id)
    WHERE institucion_id IS NULL;

CREATE UNIQUE INDEX uq_usuario_rol_institucion
    ON usuario_rol(usuario_id, rol_id, institucion_id)
    WHERE institucion_id IS NOT NULL;

CREATE TABLE evento_auditoria (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id        BIGINT REFERENCES usuario_admin(id),
    accion          VARCHAR(80) NOT NULL,
    entidad_tipo    VARCHAR(80) NOT NULL,
    entidad_id      VARCHAR(100),
    antes           JSONB,
    despues         JSONB,
    ip_hash         VARCHAR(64),
    user_agent      VARCHAR(300),
    ocurrido_en     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Completa las FK editoriales después de crear usuario_admin.
ALTER TABLE tramite_version
    ADD CONSTRAINT fk_version_creado_por
        FOREIGN KEY (creado_por) REFERENCES usuario_admin(id),
    ADD CONSTRAINT fk_version_revisado_por
        FOREIGN KEY (revisado_por) REFERENCES usuario_admin(id),
    ADD CONSTRAINT fk_version_aprobado_por
        FOREIGN KEY (aprobado_por) REFERENCES usuario_admin(id);

ALTER TABLE archivo_multimedia
    ADD CONSTRAINT fk_archivo_creado_por
        FOREIGN KEY (creado_por) REFERENCES usuario_admin(id);

-- -----------------------------------------------------------------------------
-- INGESTA Y REVISIÓN (SCRAPING / API / CARGA MANUAL)
-- -----------------------------------------------------------------------------
CREATE TABLE fuente_ingesta (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id      BIGINT REFERENCES institucion(id),
    nombre              VARCHAR(180) NOT NULL,
    tipo                VARCHAR(20) NOT NULL
                        CHECK (tipo IN ('web', 'pdf', 'api', 'manual')),
    url                 TEXT NOT NULL,
    frecuencia_cron     VARCHAR(80),
    configuracion       JSONB NOT NULL DEFAULT '{}'::jsonb,
    estado              VARCHAR(20) NOT NULL DEFAULT 'pausada'
                        CHECK (estado IN ('activa', 'pausada', 'error')),
    ultima_ejecucion_en TIMESTAMPTZ,
    proxima_ejecucion_en TIMESTAMPTZ,
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (url),
    CHECK (jsonb_typeof(configuracion) = 'object')
);

CREATE TABLE ejecucion_ingesta (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    fuente_ingesta_id   BIGINT NOT NULL REFERENCES fuente_ingesta(id),
    estado              VARCHAR(20) NOT NULL
                        CHECK (estado IN ('iniciada', 'exitosa', 'parcial', 'fallida')),
    http_status         SMALLINT,
    hash_contenido      VARCHAR(64),
    registros_leidos    INTEGER NOT NULL DEFAULT 0,
    candidatos_creados INTEGER NOT NULL DEFAULT 0,
    mensaje_error       TEXT,
    iniciada_en         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finalizada_en       TIMESTAMPTZ
);

CREATE TABLE candidato_ingesta (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ejecucion_id        UUID NOT NULL REFERENCES ejecucion_ingesta(id) ON DELETE CASCADE,
    tramite_id_sugerido BIGINT REFERENCES tramite(id),
    datos_extraidos     JSONB NOT NULL,
    texto_crudo         TEXT,
    hash_contenido      VARCHAR(64) NOT NULL,
    confianza           NUMERIC(5,4) CHECK (confianza BETWEEN 0 AND 1),
    estado              VARCHAR(20) NOT NULL DEFAULT 'pendiente'
                        CHECK (estado IN ('pendiente', 'aceptado', 'rechazado', 'duplicado')),
    revisado_por        BIGINT REFERENCES usuario_admin(id),
    revisado_en         TIMESTAMPTZ,
    UNIQUE (ejecucion_id, hash_contenido),
    CHECK (jsonb_typeof(datos_extraidos) = 'object')
);

-- -----------------------------------------------------------------------------
-- RAG: FRAGMENTOS, EMBEDDINGS Y TRAZABILIDAD DE RESPUESTA
-- -----------------------------------------------------------------------------
CREATE TABLE fragmento_conocimiento (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tramite_version_id  BIGINT NOT NULL REFERENCES tramite_version(id) ON DELETE CASCADE,
    tipo                VARCHAR(30) NOT NULL
                        CHECK (tipo IN ('resumen', 'requisito', 'paso', 'costo',
                                        'plazo', 'advertencia', 'oficina', 'resultado')),
    referencia_id       BIGINT,
    contenido           TEXT NOT NULL,
    metadatos           JSONB NOT NULL DEFAULT '{}'::jsonb,
    hash_contenido      VARCHAR(64) NOT NULL,
    embedding           vector(768),
    modelo_embedding    VARCHAR(100),
    estado_embedding    VARCHAR(20) NOT NULL DEFAULT 'pendiente'
                        CHECK (estado_embedding IN ('pendiente', 'procesando',
                                                    'listo', 'error', 'obsoleto')),
    generado_en         TIMESTAMPTZ,
    UNIQUE (tramite_version_id, tipo, hash_contenido),
    CHECK (jsonb_typeof(metadatos) = 'object'),
    CHECK ((estado_embedding = 'listo' AND embedding IS NOT NULL)
           OR estado_embedding <> 'listo')
);

CREATE INDEX idx_fragmento_embedding_hnsw
    ON fragmento_conocimiento
    USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

CREATE TABLE trabajo_embedding (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    fragmento_id        UUID NOT NULL REFERENCES fragmento_conocimiento(id) ON DELETE CASCADE,
    modelo              VARCHAR(100) NOT NULL,
    estado              VARCHAR(20) NOT NULL DEFAULT 'pendiente'
                        CHECK (estado IN ('pendiente', 'procesando', 'completado', 'fallido')),
    intentos            SMALLINT NOT NULL DEFAULT 0,
    error_detalle       TEXT,
    disponible_desde    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    iniciado_en         TIMESTAMPTZ,
    completado_en       TIMESTAMPTZ
);

-- -----------------------------------------------------------------------------
-- PRIVACIDAD, CONVERSACIONES Y CALIDAD
-- -----------------------------------------------------------------------------
CREATE TABLE sesion_anonima (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    identificador_hash  VARCHAR(64) NOT NULL UNIQUE,
    idioma              VARCHAR(10) NOT NULL DEFAULT 'es-BO',
    municipio_id        BIGINT REFERENCES municipio(id),
    consentimiento_analytics BOOLEAN NOT NULL DEFAULT FALSE,
    creada_en           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expira_en           TIMESTAMPTZ NOT NULL,
    ultima_actividad_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (expira_en > creada_en)
);

CREATE TABLE conversacion (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sesion_id           UUID NOT NULL REFERENCES sesion_anonima(id) ON DELETE CASCADE,
    titulo              VARCHAR(180),
    estado              VARCHAR(20) NOT NULL DEFAULT 'activa'
                        CHECK (estado IN ('activa', 'cerrada', 'eliminada')),
    creada_en           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    cerrada_en          TIMESTAMPTZ
);

CREATE TABLE mensaje_conversacion (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversacion_id     UUID NOT NULL REFERENCES conversacion(id) ON DELETE CASCADE,
    rol                 VARCHAR(15) NOT NULL CHECK (rol IN ('usuario', 'asistente', 'sistema')),
    contenido           TEXT NOT NULL,
    modelo              VARCHAR(100),
    tokens_entrada      INTEGER,
    tokens_salida       INTEGER,
    latencia_ms         INTEGER CHECK (latencia_ms >= 0),
    estado_seguridad    VARCHAR(20) NOT NULL DEFAULT 'permitido'
                        CHECK (estado_seguridad IN ('permitido', 'bloqueado', 'revisar')),
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE recuperacion_rag (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    mensaje_usuario_id  UUID NOT NULL REFERENCES mensaje_conversacion(id) ON DELETE CASCADE,
    consulta_normalizada TEXT,
    modelo_embedding    VARCHAR(100),
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uq_recuperacion_mensaje_usuario
    ON recuperacion_rag(mensaje_usuario_id);

CREATE TABLE cita_rag (
    recuperacion_id     UUID NOT NULL REFERENCES recuperacion_rag(id) ON DELETE CASCADE,
    fragmento_id       UUID NOT NULL REFERENCES fragmento_conocimiento(id),
    posicion           SMALLINT NOT NULL CHECK (posicion > 0),
    similitud          NUMERIC(7,6) CHECK (similitud BETWEEN -1 AND 1),
    incluida_en_prompt BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (recuperacion_id, fragmento_id)
);

CREATE TABLE feedback_respuesta (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    mensaje_asistente_id UUID NOT NULL REFERENCES mensaje_conversacion(id) ON DELETE CASCADE,
    valoracion          SMALLINT NOT NULL CHECK (valoracion IN (-1, 1)),
    motivo              VARCHAR(40)
                        CHECK (motivo IN ('incorrecta', 'desactualizada', 'incompleta',
                                          'confusa', 'util', 'otro')),
    comentario          TEXT,
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (mensaje_asistente_id)
);

CREATE TABLE reporte_ciudadano (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tramite_id          BIGINT REFERENCES tramite(id),
    oficina_id          BIGINT REFERENCES oficina(id),
    tipo                VARCHAR(30) NOT NULL
                        CHECK (tipo IN ('dato_incorrecto', 'dato_desactualizado',
                                        'oficina_cerrada', 'costo_distinto',
                                        'requisito_distinto', 'otro')),
    descripcion         TEXT NOT NULL,
    correo_contacto_cifrado BYTEA,
    estado              VARCHAR(20) NOT NULL DEFAULT 'nuevo'
                        CHECK (estado IN ('nuevo', 'en_revision', 'resuelto', 'descartado')),
    asignado_a          BIGINT REFERENCES usuario_admin(id),
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resuelto_en         TIMESTAMPTZ
);

-- -----------------------------------------------------------------------------
-- ÍNDICES
-- -----------------------------------------------------------------------------
CREATE INDEX idx_municipio_departamento ON municipio(departamento_id);
CREATE INDEX idx_archivo_original ON archivo_multimedia(original_id);
CREATE INDEX idx_archivo_estado ON archivo_multimedia(estado, creado_en DESC);
CREATE INDEX idx_archivo_creado_por ON archivo_multimedia(creado_por);
CREATE UNIQUE INDEX uq_archivo_original_sha256
    ON archivo_multimedia(sha256)
    WHERE original_id IS NULL AND estado <> 'eliminado';
CREATE INDEX idx_institucion_logo ON institucion(logo_archivo_id);
CREATE INDEX idx_institucion_padre ON institucion(institucion_padre_id);
CREATE INDEX idx_institucion_reemplazo ON institucion(reemplazada_por_id);
CREATE INDEX idx_institucion_alias_trgm
    ON institucion_alias USING gin(normalizado gin_trgm_ops);
CREATE INDEX idx_oficina_institucion ON oficina(institucion_id, estado);
CREATE INDEX idx_oficina_municipio ON oficina(municipio_id);
CREATE INDEX idx_oficina_contacto_oficina ON oficina_contacto(oficina_id);
CREATE UNIQUE INDEX uq_oficina_contacto_principal
    ON oficina_contacto(oficina_id, tipo)
    WHERE es_principal;
CREATE INDEX idx_horario_oficina ON horario_oficina(oficina_id, dia_semana);
CREATE INDEX idx_excepcion_oficina ON excepcion_atencion(oficina_id, fecha);
CREATE INDEX idx_categoria_padre ON categoria(padre_id);
CREATE INDEX idx_tramite_institucion ON tramite(institucion_id, estado);
CREATE INDEX idx_tramite_categoria ON tramite(categoria_id);
CREATE INDEX idx_tramite_reemplazo ON tramite(reemplaza_tramite_id);
CREATE INDEX idx_tramite_alias_trgm
    ON tramite_alias USING gin(normalizado gin_trgm_ops);
CREATE INDEX idx_version_estado ON tramite_version(estado_editorial, proxima_revision_en);
CREATE INDEX idx_version_creado_por ON tramite_version(creado_por);
CREATE INDEX idx_version_revisado_por ON tramite_version(revisado_por);
CREATE INDEX idx_version_aprobado_por ON tramite_version(aprobado_por);
CREATE INDEX idx_version_titulo_trgm
    ON tramite_version
    USING gin(public.normalizar_busqueda(titulo) gin_trgm_ops);
CREATE INDEX idx_fuente_institucion ON fuente_oficial(institucion_id);
CREATE INDEX idx_version_fuente_fuente ON tramite_version_fuente(fuente_id);
CREATE INDEX idx_tramite_oficina_oficina ON tramite_oficina(oficina_id);
CREATE INDEX idx_requisito_version_orden ON requisito_tramite(tramite_version_id, orden);
CREATE INDEX idx_requisito_modalidad ON requisito_tramite(modalidad_id);
CREATE INDEX idx_paso_version_numero ON paso_tramite(tramite_version_id, numero);
CREATE INDEX idx_paso_modalidad ON paso_tramite(modalidad_id);
CREATE INDEX idx_costo_version ON costo_tramite(tramite_version_id);
CREATE INDEX idx_costo_modalidad ON costo_tramite(modalidad_id);
CREATE INDEX idx_resultado_version ON resultado_tramite(tramite_version_id);
CREATE INDEX idx_fuente_consultada ON fuente_oficial(consultado_en DESC);
CREATE INDEX idx_usuario_rol_rol ON usuario_rol(rol_id);
CREATE INDEX idx_usuario_rol_institucion ON usuario_rol(institucion_id);
CREATE INDEX idx_sesion_admin_usuario
    ON sesion_admin(usuario_id, expira_en DESC);
CREATE INDEX idx_sesion_admin_activa
    ON sesion_admin(expira_en)
    WHERE revocada_en IS NULL;
CREATE INDEX idx_auditoria_actor ON evento_auditoria(actor_id, ocurrido_en DESC);
CREATE INDEX idx_auditoria_entidad ON evento_auditoria(entidad_tipo, entidad_id, ocurrido_en DESC);
CREATE INDEX idx_fuente_ingesta_institucion ON fuente_ingesta(institucion_id);
CREATE INDEX idx_ingesta_estado ON ejecucion_ingesta(estado, iniciada_en DESC);
CREATE INDEX idx_ingesta_fuente ON ejecucion_ingesta(fuente_ingesta_id, iniciada_en DESC);
CREATE INDEX idx_candidato_estado ON candidato_ingesta(estado);
CREATE INDEX idx_candidato_tramite ON candidato_ingesta(tramite_id_sugerido);
CREATE INDEX idx_candidato_revisor ON candidato_ingesta(revisado_por);
CREATE INDEX idx_fragmento_version ON fragmento_conocimiento(tramite_version_id);
CREATE INDEX idx_trabajo_fragmento ON trabajo_embedding(fragmento_id);
CREATE UNIQUE INDEX uq_trabajo_embedding_activo
    ON trabajo_embedding(fragmento_id, modelo)
    WHERE estado IN ('pendiente', 'procesando');
CREATE INDEX idx_conversacion_sesion ON conversacion(sesion_id, creada_en DESC);
CREATE INDEX idx_mensaje_conversacion ON mensaje_conversacion(conversacion_id, creado_en);
CREATE INDEX idx_cita_fragmento ON cita_rag(fragmento_id);
CREATE INDEX idx_reporte_estado ON reporte_ciudadano(estado, creado_en);
CREATE INDEX idx_reporte_tramite ON reporte_ciudadano(tramite_id);
CREATE INDEX idx_reporte_oficina ON reporte_ciudadano(oficina_id);
CREATE INDEX idx_reporte_asignado ON reporte_ciudadano(asignado_a);

-- -----------------------------------------------------------------------------
-- TRIGGERS Y REGLAS DE INTEGRIDAD
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION establecer_actualizado_en()
RETURNS TRIGGER AS $$
BEGIN
    NEW.actualizado_en = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_institucion_actualizada
BEFORE UPDATE ON institucion
FOR EACH ROW EXECUTE FUNCTION establecer_actualizado_en();

CREATE TRIGGER trg_archivo_actualizado
BEFORE UPDATE ON archivo_multimedia
FOR EACH ROW EXECUTE FUNCTION establecer_actualizado_en();

CREATE TRIGGER trg_oficina_actualizada
BEFORE UPDATE ON oficina
FOR EACH ROW EXECUTE FUNCTION establecer_actualizado_en();

CREATE TRIGGER trg_tramite_actualizado
BEFORE UPDATE ON tramite
FOR EACH ROW EXECUTE FUNCTION establecer_actualizado_en();

CREATE TRIGGER trg_usuario_actualizado
BEFORE UPDATE ON usuario_admin
FOR EACH ROW EXECUTE FUNCTION establecer_actualizado_en();

CREATE OR REPLACE FUNCTION proteger_version_publicada()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.estado_editorial = 'publicada' THEN
            RAISE EXCEPTION
                'Una versión publicada no se elimina; debe marcarse como reemplazada.';
        END IF;
        RETURN OLD;
    END IF;

    IF OLD.estado_editorial = 'publicada' THEN
        -- El contenido queda congelado. Solo se permite cerrar su vigencia,
        -- marcarla como reemplazada y reprogramar la revisión.
        IF (to_jsonb(NEW) - ARRAY[
                'estado_editorial', 'valido_hasta', 'proxima_revision_en'
            ]) IS DISTINCT FROM
           (to_jsonb(OLD) - ARRAY[
                'estado_editorial', 'valido_hasta', 'proxima_revision_en'
            ]) THEN
            RAISE EXCEPTION
                'El contenido publicado es inmutable. Cree una nueva versión editorial.';
        END IF;

        IF NEW.estado_editorial NOT IN ('publicada', 'reemplazada') THEN
            RAISE EXCEPTION
                'Una versión publicada solo puede pasar a reemplazada.';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_version_publicada_inmutable
BEFORE UPDATE OR DELETE ON tramite_version
FOR EACH ROW EXECUTE FUNCTION proteger_version_publicada();

-- -----------------------------------------------------------------------------
-- VISTAS DE LECTURA PÚBLICA
-- -----------------------------------------------------------------------------
CREATE VIEW vw_tramite_publicado AS
SELECT
    t.id,
    t.codigo,
    t.slug,
    t.institucion_id,
    i.nombre AS institucion,
    i.sigla,
    t.categoria_id,
    c.nombre AS categoria,
    v.id AS version_id,
    v.numero_version,
    v.titulo,
    v.resumen,
    v.descripcion,
    v.publico_objetivo,
    v.resultado_esperado,
    v.advertencias,
    v.plazo_texto,
    v.vigencia_resultado_texto,
    v.requiere_cita,
    v.url_inicio,
    v.verificado_en,
    v.proxima_revision_en,
    v.publicado_en
FROM tramite t
JOIN institucion i ON i.id = t.institucion_id
LEFT JOIN categoria c ON c.id = t.categoria_id
JOIN tramite_version v ON v.tramite_id = t.id
WHERE t.estado = 'activo'
  AND i.estado = 'activa'
  AND v.estado_editorial = 'publicada'
  AND (v.valido_desde IS NULL OR v.valido_desde <= NOW())
  AND (v.valido_hasta IS NULL OR v.valido_hasta > NOW());

CREATE VIEW vw_oficina_horario AS
SELECT
    o.id AS oficina_id,
    o.nombre AS oficina,
    o.direccion,
    m.nombre AS municipio,
    d.nombre AS departamento,
    h.dia_semana,
    h.hora_apertura,
    h.hora_cierre,
    h.con_cita
FROM oficina o
LEFT JOIN municipio m ON m.id = o.municipio_id
LEFT JOIN departamento d ON d.id = m.departamento_id
LEFT JOIN horario_oficina h ON h.oficina_id = o.id
WHERE o.estado IN ('activa', 'temporal');

-- =============================================================================
-- DATOS DE DESARROLLO
-- =============================================================================

INSERT INTO departamento (codigo, nombre) VALUES
('LP', 'La Paz'), ('CB', 'Cochabamba'), ('SC', 'Santa Cruz'),
('OR', 'Oruro'), ('PT', 'Potosí'), ('CH', 'Chuquisaca'),
('TJ', 'Tarija'), ('BE', 'Beni'), ('PA', 'Pando');

INSERT INTO municipio (departamento_id, codigo_ine, nombre)
SELECT d.id, x.codigo_ine, x.nombre
FROM (VALUES
    ('LP', '020101', 'La Paz'),
    ('LP', '020105', 'El Alto'),
    ('CB', '030101', 'Cochabamba'),
    ('SC', '070101', 'Santa Cruz de la Sierra'),
    ('CH', '010101', 'Sucre')
) AS x(depto, codigo_ine, nombre)
JOIN departamento d ON d.codigo = x.depto;

INSERT INTO categoria (codigo, nombre, icono, orden) VALUES
('identidad', 'Identidad y documentos', 'badge', 10),
('registro-civil', 'Registro civil', 'family_restroom', 20),
('migracion', 'Migración y viajes', 'flight', 30),
('empresas', 'Empresas y comercio', 'business', 40),
('tributario', 'Impuestos y tributos', 'receipt_long', 50),
('transporte', 'Transporte y conducción', 'directions_car', 60),
('seguridad', 'Seguridad y antecedentes', 'verified_user', 70);

INSERT INTO institucion
    (codigo, nombre, sigla, tipo, sitio_web, estado)
VALUES
('SEGIP', 'Servicio General de Identificación Personal', 'SEGIP', 'publica',
 'https://www.segip.gob.bo/', 'activa'),
('SEGELIC', 'Servicio General de Licencias de Conducir', 'SEGELIC', 'publica',
 'https://www.segip.gob.bo/', 'activa'),
('SERECI', 'Servicio de Registro Cívico', 'SERECI', 'publica',
 'https://www.oep.org.bo/registro-civico/', 'activa'),
('DIGEMIG', 'Dirección General de Migración', 'DIGEMIG', 'publica',
 'https://www.migracion.gob.bo/', 'activa'),
('SIN', 'Servicio de Impuestos Nacionales', 'SIN', 'publica',
 'https://www.impuestos.gob.bo/', 'activa'),
('SEPREC', 'Servicio Plurinacional de Registro de Comercio', 'SEPREC', 'publica',
 'https://www.seprec.gob.bo/', 'activa'),
('POLICIA-DNSTA', 'Dirección Nacional de Servicios Técnicos Auxiliares',
 'DNSTA', 'publica', 'https://antecedentes.policia.bo/', 'activa');

INSERT INTO institucion_alias (institucion_id, alias)
SELECT i.id, x.alias
FROM (VALUES
    ('SEGIP', 'Identificación'),
    ('SEGIP', 'Oficina del carnet'),
    ('SEGELIC', 'Licencias'),
    ('SERECI', 'Registro Civil'),
    ('DIGEMIG', 'Migración'),
    ('SEPREC', 'Registro de Comercio'),
    ('SEPREC', 'FUNDEMPRESA'),
    ('POLICIA-DNSTA', 'Antecedentes policiales')
) AS x(codigo, alias)
JOIN institucion i ON i.codigo = x.codigo;

-- Oficinas de muestra. Solo se publican cuando tienen fecha de verificación.
INSERT INTO oficina
    (institucion_id, municipio_id, codigo, nombre, tipo, direccion,
     latitud, longitud, requiere_cita, estado, verificado_en)
SELECT i.id, m.id, x.codigo_oficina, x.nombre, x.tipo, x.direccion,
       x.latitud, x.longitud, x.requiere_cita, 'activa',
       TIMESTAMPTZ '2026-07-25 12:00:00-04'
FROM (VALUES
    ('DIGEMIG', 'La Paz', 'LP-CENTRAL', 'Oficina Central DIGEMIG',
     'oficina', 'Av. Camacho N.º 1468, zona Central',
     NULL::numeric, NULL::numeric, false),
    ('SEPREC', 'La Paz', 'LP-NACIONAL', 'Oficina Nacional Sopocachi',
     'oficina', 'Av. 20 de Octubre N.º 2331, Sopocachi',
     NULL::numeric, NULL::numeric, false),
    ('SEGELIC', 'La Paz', 'LP-SAN-PEDRO', 'SEGELIC La Paz San Pedro',
     'oficina', 'Av. 20 de Octubre N.º 1636',
     NULL::numeric, NULL::numeric, false)
) AS x(inst, municipio, codigo_oficina, nombre, tipo, direccion,
       latitud, longitud, requiere_cita)
JOIN institucion i ON i.codigo = x.inst
JOIN municipio m ON m.nombre = x.municipio;

-- Fuentes oficiales consultadas para construir la semilla.
INSERT INTO fuente_oficial
    (institucion_id, tipo, titulo, url, fecha_documento,
     autoridad_emisora, consultado_en, estado)
SELECT i.id, x.tipo, x.titulo, x.url, x.fecha_documento, x.autoridad,
       TIMESTAMPTZ '2026-07-25 12:00:00-04', x.estado
FROM (VALUES
    ('SEPREC', 'pagina_web',
     'Trámite 1 - Inscripción de Comerciante Individual o Empresa Unipersonal',
     'https://www.seprec.gob.bo/index.php/tramite1/', NULL::date,
     'SEPREC', 'vigente'),
    ('SEPREC', 'pagina_web', 'Ficha institucional SEPREC en gob.bo',
     'https://www.gob.bo/entidades/servicio-plurinacional-de-registro-de-comercio',
     NULL::date, 'AGETIC / SEPREC', 'vigente'),
    ('DIGEMIG', 'pdf', 'Libreta de Pasaporte Corriente - ficha de trámite 30',
     'https://migracion.gob.bo/sites/default/files/2024-08/RM%2030.%20LIBRETA%20DE%20PASAPORTE%20CORRIENTE%20%281%29.pdf',
     DATE '2024-08-01', 'Dirección General de Migración', 'por_verificar'),
    ('SIN', 'pagina_web', 'Proceso de inscripción al Registro Nacional de Contribuyentes',
     'https://siatinfo.impuestos.gob.bo/index.php/requisitos-para-la-inscripcion/procesos-de-insccripcion',
     NULL::date, 'Servicio de Impuestos Nacionales', 'vigente'),
    ('SIN', 'pagina_web', 'Requisitos para obtener el NIT para personas',
     'https://siatinfo.impuestos.gob.bo/index.php/requisitos-para-la-inscripcion/requisitos-para-obtener-el-nit-para-personas',
     NULL::date, 'Servicio de Impuestos Nacionales', 'vigente'),
    ('POLICIA-DNSTA', 'pagina_web', 'Certificado de Antecedentes Policiales',
     'https://antecedentes.policia.bo/?page_id=1996',
     NULL::date, 'Policía Boliviana - DNSTA', 'por_verificar')
) AS x(inst, tipo, titulo, url, fecha_documento, autoridad, estado)
JOIN institucion i ON i.codigo = x.inst;

-- Trámites: tres publicables y dos borradores que ejercitan el flujo editorial.
INSERT INTO tramite
    (codigo, slug, institucion_id, categoria_id, codigo_oficial, alcance)
SELECT x.codigo, x.slug, i.id, c.id, x.codigo_oficial, 'nacional'
FROM (VALUES
    ('SEPREC-01', 'inscripcion-empresa-unipersonal', 'SEPREC', 'empresas', '01'),
    ('DIGEMIG-30', 'pasaporte-corriente', 'DIGEMIG', 'migracion', '30'),
    ('SIN-RNC-PN', 'inscripcion-nit-persona-natural', 'SIN', 'tributario', 'RNC-PN'),
    ('SEGIP-CI-01', 'cedula-identidad-primera-vez', 'SEGIP', 'identidad', 'CI-01'),
    ('SEGELIC-LC-01', 'licencia-conducir-primera-vez', 'SEGELIC', 'transporte', 'LC-01')
) AS x(codigo, slug, inst, categoria, codigo_oficial)
JOIN institucion i ON i.codigo = x.inst
JOIN categoria c ON c.codigo = x.categoria;

INSERT INTO tramite_alias (tramite_id, alias, tipo)
SELECT t.id, x.alias, x.tipo
FROM (VALUES
    ('SEPREC-01', 'Registrar empresa unipersonal', 'popular'),
    ('SEPREC-01', 'FUNDEMPRESA empresa unipersonal', 'anterior'),
    ('DIGEMIG-30', 'Sacar pasaporte', 'popular'),
    ('SIN-RNC-PN', 'Sacar NIT', 'popular'),
    ('SEGIP-CI-01', 'Sacar carnet', 'popular'),
    ('SEGIP-CI-01', 'Carnet de identidad', 'popular'),
    ('SEGELIC-LC-01', 'Sacar licencia', 'popular')
) AS x(codigo, alias, tipo)
JOIN tramite t ON t.codigo = x.codigo;

-- Las tres primeras versiones están publicadas. Las otras dos quedan en borrador
-- para no presentar como ciertos requisitos que todavía no fueron verificados.
INSERT INTO tramite_version
    (tramite_id, numero_version, estado_editorial, titulo, resumen, descripcion,
     publico_objetivo, resultado_esperado, advertencias, plazo_texto,
     requiere_cita, url_inicio, valido_desde, verificado_en,
     proxima_revision_en, publicado_en, hash_contenido)
SELECT t.id, 1, x.estado, x.titulo, x.resumen, x.descripcion,
       x.publico_objetivo, x.resultado, x.advertencias, x.plazo,
       x.requiere_cita, x.url_inicio,
       CASE WHEN x.estado = 'publicada' THEN TIMESTAMPTZ '2026-07-25 12:00:00-04' END,
       CASE WHEN x.estado = 'publicada' THEN TIMESTAMPTZ '2026-07-25 12:00:00-04' END,
       CASE WHEN x.estado = 'publicada' THEN TIMESTAMPTZ '2026-10-25 12:00:00-04' END,
       CASE WHEN x.estado = 'publicada' THEN TIMESTAMPTZ '2026-07-25 12:00:00-04' END,
       encode(digest(x.descripcion, 'sha256'), 'hex')
FROM (VALUES
    ('SEPREC-01', 'publicada',
     'Inscripción de Comerciante Individual o Empresa Unipersonal',
     'Registro virtual de una empresa unipersonal ante el SEPREC.',
     'Permite inscribir a una persona natural que realiza habitualmente una actividad comercial y obtener su Matrícula de Comercio.',
     'Personas naturales que iniciarán una actividad comercial como empresa unipersonal.',
     'Certificado de Matrícula de Comercio con código de validación QR.',
     'Una persona natural no puede registrar más de una empresa unipersonal. Actividades reguladas requieren autorización del ente competente.',
     '24 horas desde el día siguiente hábil a la fecha del pago, según la ficha oficial consultada.',
     false, 'https://tramites.seprec.gob.bo/'),
    ('DIGEMIG-30', 'publicada',
     'Libreta de Pasaporte Corriente',
     'Emisión o renovación presencial y personal del pasaporte boliviano.',
     'La Dirección General de Migración emite el pasaporte corriente dentro de Bolivia. La información cambia según mayoría de edad, renovación, pérdida y situación de los progenitores.',
     'Ciudadanas y ciudadanos bolivianos que requieren un documento de viaje.',
     'Libreta de pasaporte corriente.',
     'La semilla modela solamente el caso base de persona mayor de edad. Consultar la ficha oficial para menores, pérdida o renovación.',
     'Consultar disponibilidad y plazo actual con DIGEMIG.',
     false, 'https://www.migracion.gob.bo/'),
    ('SIN-RNC-PN', 'publicada',
     'Inscripción al RNC y obtención de NIT para persona natural',
     'Inscripción tributaria en línea o presencial para una persona natural.',
     'El Servicio de Impuestos Nacionales permite la inscripción al Registro Nacional de Contribuyentes en línea o en plataformas de atención. Los requisitos dependen del sector económico.',
     'Personas naturales que desarrollarán una actividad económica alcanzada por obligaciones tributarias.',
     'NIT y credenciales de acceso a SIAT en Línea.',
     'Los requisitos varían por actividad y régimen tributario. El sistema debe preguntar el sector económico antes de mostrar una lista definitiva.',
     'Variable según modalidad y revisión de documentos.',
     false, 'https://siat.impuestos.gob.bo/'),
    ('SEGIP-CI-01', 'borrador',
     'Cédula de identidad por primera vez',
     'Borrador pendiente de verificación oficial.',
     'Registro de prueba para ejercitar revisión editorial. No debe aparecer en la API pública hasta validar requisitos, costo, oficinas y fuente.',
     'Ciudadanía boliviana.', 'Cédula de identidad.',
     'NO PUBLICAR: información pendiente de verificación.', NULL,
     false, NULL),
    ('SEGELIC-LC-01', 'borrador',
     'Licencia para conducir por primera vez',
     'Borrador pendiente de verificación oficial.',
     'Registro de prueba para ejercitar condiciones por categoría, edad y tipo de vehículo.',
     'Personas habilitadas para conducir.', 'Licencia para conducir.',
     'NO PUBLICAR: falta validar categorías, evaluaciones, costos y requisitos.',
     NULL, false, NULL)
) AS x(codigo, estado, titulo, resumen, descripcion, publico_objetivo,
       resultado, advertencias, plazo, requiere_cita, url_inicio)
JOIN tramite t ON t.codigo = x.codigo;

INSERT INTO tramite_version_fuente (tramite_version_id, fuente_id, uso)
SELECT v.id, f.id, x.uso
FROM (VALUES
    ('SEPREC-01', 'https://www.seprec.gob.bo/index.php/tramite1/', 'principal'),
    ('SEPREC-01', 'https://www.seprec.gob.bo/index.php/tramite1/', 'costos'),
    ('DIGEMIG-30',
     'https://migracion.gob.bo/sites/default/files/2024-08/RM%2030.%20LIBRETA%20DE%20PASAPORTE%20CORRIENTE%20%281%29.pdf',
     'principal'),
    ('SIN-RNC-PN',
     'https://siatinfo.impuestos.gob.bo/index.php/requisitos-para-la-inscripcion/procesos-de-insccripcion',
     'principal'),
    ('SIN-RNC-PN',
     'https://siatinfo.impuestos.gob.bo/index.php/requisitos-para-la-inscripcion/requisitos-para-obtener-el-nit-para-personas',
     'requisitos')
) AS x(codigo, url, uso)
JOIN tramite t ON t.codigo = x.codigo
JOIN tramite_version v ON v.tramite_id = t.id AND v.numero_version = 1
JOIN fuente_oficial f ON f.url = x.url;

INSERT INTO modalidad_tramite
    (tramite_version_id, tipo, nombre, descripcion, url_inicio, requiere_cita, orden)
SELECT v.id, x.tipo, x.nombre, x.descripcion, x.url_inicio, x.requiere_cita, x.orden
FROM (VALUES
    ('SEPREC-01', 'en_linea', 'Trámite virtual',
     'Formulario y pago mediante el portal del Registro de Comercio.',
     'https://tramites.seprec.gob.bo/', false, 1),
    ('DIGEMIG-30', 'presencial', 'Atención presencial',
     'El registro biométrico y la solicitud son personales.',
     NULL, false, 1),
    ('SIN-RNC-PN', 'en_linea', 'Inscripción en línea',
     'Digitalizar y adjuntar en PDF los documentos que correspondan.',
     'https://siat.impuestos.gob.bo/', false, 1),
    ('SIN-RNC-PN', 'presencial', 'Inscripción en plataforma',
     'Presentar los documentos originales en la plataforma del SIN.',
     NULL, false, 2)
) AS x(codigo, tipo, nombre, descripcion, url_inicio, requiere_cita, orden)
JOIN tramite t ON t.codigo = x.codigo
JOIN tramite_version v ON v.tramite_id = t.id AND v.numero_version = 1;

INSERT INTO requisito_tramite
    (tramite_version_id, modalidad_id, codigo, titulo, descripcion,
     obligatorio, cantidad_originales, cantidad_copias, formato,
     grupo_alternativa, aplica_si, orden)
SELECT v.id, m.id, x.req_codigo, x.titulo, x.descripcion,
       x.obligatorio, x.originales, x.copias, x.formato,
       x.grupo_alternativa, x.aplica_si::jsonb, x.orden
FROM (VALUES
    ('SEPREC-01', 'en_linea', 'FORM-VIRTUAL', 'Formulario Virtual de Inscripción',
     'Llenado por el propietario con carácter de declaración jurada y aprobación mediante Ciudadanía Digital.',
     true, 0, 0, 'formulario web', NULL, '{}', 1),
    ('SEPREC-01', 'en_linea', 'PAGO', 'Pago del arancel',
     'Realizar el pago por la plataforma habilitada.', true, 0, 0,
     'pago electrónico', NULL, '{}', 2),
    ('SEPREC-01', 'en_linea', 'AUT-REGULADOR', 'Autorización del ente regulador',
     'Solo para actividades reguladas por ley.', false, 0, 0, 'PDF',
     NULL, '{"actividad_regulada": true}', 3),
    ('DIGEMIG-30', 'presencial', 'CI', 'Cédula de identidad original',
     'Se presenta para contrastación y se devuelve inmediatamente.',
     true, 1, 0, 'original', NULL, '{"edad": "mayor_o_igual_18"}', 1),
    ('DIGEMIG-30', 'presencial', 'PASAPORTE-ANTERIOR', 'Pasaporte anterior vigente',
     'Aplica en renovación cuando el pasaporte anterior todavía está vigente.',
     false, 1, 0, 'original', NULL, '{"tipo_solicitud": "renovacion", "pasaporte_vigente": true}', 2),
    ('SIN-RNC-PN', 'en_linea', 'DOC-SECTOR', 'Documentación según sector económico',
     'La lista exacta se determina por actividad y régimen; los documentos se adjuntan en PDF.',
     true, 0, 0, 'PDF', NULL, '{"requiere_clasificacion_sector": true}', 1),
    ('SIN-RNC-PN', 'presencial', 'DOC-SECTOR', 'Documentación según sector económico',
     'La lista exacta se determina por actividad y régimen; se presentan originales.',
     true, 1, 0, 'original', NULL, '{"requiere_clasificacion_sector": true}', 1)
) AS x(codigo, modalidad, req_codigo, titulo, descripcion, obligatorio,
       originales, copias, formato, grupo_alternativa, aplica_si, orden)
JOIN tramite t ON t.codigo = x.codigo
JOIN tramite_version v ON v.tramite_id = t.id AND v.numero_version = 1
JOIN modalidad_tramite m
  ON m.tramite_version_id = v.id AND m.tipo = x.modalidad;

INSERT INTO paso_tramite
    (tramite_version_id, modalidad_id, numero, titulo, descripcion, url_accion)
SELECT v.id, m.id, x.numero, x.titulo, x.descripcion, x.url_accion
FROM (VALUES
    ('SEPREC-01', 'en_linea', 1, 'Ingresar al portal',
     'Acceder con las credenciales de Ciudadanía Digital del propietario.',
     'https://tramites.seprec.gob.bo/'),
    ('SEPREC-01', 'en_linea', 2, 'Completar la solicitud',
     'Llenar el formulario, realizar el control de homonimia y adjuntar autorización si corresponde.',
     NULL),
    ('SEPREC-01', 'en_linea', 3, 'Realizar el pago',
     'Pagar mediante la plataforma habilitada y conservar el comprobante.',
     NULL),
    ('SEPREC-01', 'en_linea', 4, 'Descargar el resultado',
     'Revisar observaciones o descargar la Matrícula desde Mis Certificados.',
     NULL),
    ('DIGEMIG-30', 'presencial', 1, 'Verificar el caso aplicable',
     'Confirmar requisitos para primera emisión, renovación, pérdida o menor de edad.',
     'https://www.migracion.gob.bo/'),
    ('DIGEMIG-30', 'presencial', 2, 'Presentarse personalmente',
     'Acudir a la oficina habilitada con los documentos del caso.',
     NULL),
    ('SIN-RNC-PN', 'en_linea', 1, 'Identificar actividad y régimen',
     'Definir el sector económico para conocer los requisitos aplicables.',
     NULL),
    ('SIN-RNC-PN', 'en_linea', 2, 'Registrar y adjuntar documentos',
     'Completar el proceso en línea y adjuntar los documentos PDF requeridos.',
     'https://siat.impuestos.gob.bo/')
) AS x(codigo, modalidad, numero, titulo, descripcion, url_accion)
JOIN tramite t ON t.codigo = x.codigo
JOIN tramite_version v ON v.tramite_id = t.id AND v.numero_version = 1
JOIN modalidad_tramite m
  ON m.tramite_version_id = v.id AND m.tipo = x.modalidad;

INSERT INTO costo_tramite
    (tramite_version_id, modalidad_id, concepto, moneda, monto,
     es_gratuito, medio_pago, instrucciones, verificado_en)
SELECT v.id, m.id, 'Arancel de inscripción de empresa unipersonal',
       'BOB', 130.00, false, 'Plataforma de pagos del SEPREC',
       'El monto corresponde a la ficha oficial consultada; verificar si cambió antes de pagar.',
       TIMESTAMPTZ '2026-07-25 12:00:00-04'
FROM tramite t
JOIN tramite_version v ON v.tramite_id = t.id AND v.numero_version = 1
JOIN modalidad_tramite m ON m.tramite_version_id = v.id AND m.tipo = 'en_linea'
WHERE t.codigo = 'SEPREC-01';

INSERT INTO resultado_tramite
    (tramite_version_id, nombre, formato, vigencia, entrega, orden)
SELECT v.id, x.nombre, x.formato, x.vigencia, x.entrega, 1
FROM (VALUES
    ('SEPREC-01', 'Certificado de Matrícula de Comercio', 'PDF con QR',
     'Sujeta a renovación conforme a normativa vigente', 'Descarga en el portal'),
    ('DIGEMIG-30', 'Libreta de pasaporte corriente', 'Documento físico',
     'Según edad y normativa vigente', 'Oficina de DIGEMIG'),
    ('SIN-RNC-PN', 'NIT y credenciales SIAT', 'Registro digital',
     'Mientras el registro permanezca activo', 'Correo y plataforma')
) AS x(codigo, nombre, formato, vigencia, entrega)
JOIN tramite t ON t.codigo = x.codigo
JOIN tramite_version v ON v.tramite_id = t.id AND v.numero_version = 1;

INSERT INTO tramite_oficina (modalidad_id, oficina_id, notas)
SELECT m.id, o.id, 'Confirmar horario y disponibilidad antes de acudir.'
FROM modalidad_tramite m
JOIN tramite_version v ON v.id = m.tramite_version_id
JOIN tramite t ON t.id = v.tramite_id
JOIN oficina o ON o.institucion_id = t.institucion_id
WHERE (t.codigo = 'DIGEMIG-30' AND o.codigo = 'LP-CENTRAL')
;

INSERT INTO etiqueta (slug, nombre) VALUES
('en-linea', 'Disponible en línea'),
('presencial', 'Requiere presencia'),
('con-costo', 'Tiene costo'),
('persona-natural', 'Persona natural');

INSERT INTO tramite_etiqueta (tramite_id, etiqueta_id)
SELECT t.id, e.id
FROM (VALUES
    ('SEPREC-01', 'en-linea'), ('SEPREC-01', 'con-costo'),
    ('SEPREC-01', 'persona-natural'), ('DIGEMIG-30', 'presencial'),
    ('SIN-RNC-PN', 'en-linea'), ('SIN-RNC-PN', 'presencial'),
    ('SIN-RNC-PN', 'persona-natural')
) AS x(codigo, etiqueta)
JOIN tramite t ON t.codigo = x.codigo
JOIN etiqueta e ON e.slug = x.etiqueta;

-- Roles. No se crean contraseñas ni tokens conocidos en el repositorio.
INSERT INTO rol (codigo, nombre, permisos) VALUES
('superadmin', 'Administrador del sistema',
 '["*"]'),
('editor', 'Editor de contenidos',
 '["catalogo:leer","version:crear","version:editar","reporte:gestionar"]'),
('revisor', 'Revisor institucional',
 '["catalogo:leer","version:revisar","version:aprobar"]'),
('analista', 'Analista de calidad',
 '["metricas:leer","feedback:leer","auditoria:leer"]');

INSERT INTO usuario_admin
    (correo, nombre, proveedor_identidad, estado)
VALUES
    ('admin.demo@invalid.local', 'Cuenta pendiente de configuración', 'local', 'pendiente');

INSERT INTO usuario_rol (usuario_id, rol_id)
SELECT u.id, r.id
FROM usuario_admin u
JOIN rol r ON r.codigo = 'superadmin'
WHERE u.correo = 'admin.demo@invalid.local';

-- Configuraciones de ingesta desactivadas hasta implementar selectores,
-- control de robots.txt, límites, hashes y revisión humana.
INSERT INTO fuente_ingesta
    (institucion_id, nombre, tipo, url, frecuencia_cron, configuracion, estado)
SELECT i.id, x.nombre, x.tipo, x.url, x.cron, x.configuracion::jsonb, 'pausada'
FROM (VALUES
    ('SEPREC', 'Ficha oficial del trámite 01', 'web',
     'https://www.seprec.gob.bo/index.php/tramite1/', '0 3 * * 1',
     '{"respeta_robots": true, "requiere_revision": true}'),
    ('SIN', 'Requisitos de inscripción RNC', 'web',
     'https://siatinfo.impuestos.gob.bo/index.php/requisitos-para-la-inscripcion/procesos-de-insccripcion',
     '0 3 * * 1',
     '{"respeta_robots": true, "requiere_revision": true}')
) AS x(inst, nombre, tipo, url, cron, configuracion)
JOIN institucion i ON i.codigo = x.inst;

-- Se crean fragmentos solo para versiones publicadas. Los embeddings quedan
-- pendientes; nunca se insertan vectores ficticios.
INSERT INTO fragmento_conocimiento
    (tramite_version_id, tipo, contenido, metadatos,
     hash_contenido, estado_embedding)
SELECT v.id, 'resumen',
       concat_ws(E'\n\n',
           'TRÁMITE: ' || v.titulo,
           'RESUMEN: ' || v.resumen,
           'DESCRIPCIÓN: ' || v.descripcion,
           CASE WHEN v.advertencias IS NOT NULL
                THEN 'ADVERTENCIAS: ' || v.advertencias END,
           CASE WHEN v.plazo_texto IS NOT NULL
                THEN 'PLAZO: ' || v.plazo_texto END),
       jsonb_build_object(
           'tramite_id', v.tramite_id,
           'version', v.numero_version,
           'verificado_en', v.verificado_en),
       encode(digest(concat_ws('|', v.titulo, v.resumen, v.descripcion,
                                    v.advertencias, v.plazo_texto), 'sha256'), 'hex'),
       'pendiente'
FROM tramite_version v
WHERE v.estado_editorial = 'publicada';

INSERT INTO fragmento_conocimiento
    (tramite_version_id, tipo, referencia_id, contenido, metadatos,
     hash_contenido, estado_embedding)
SELECT r.tramite_version_id, 'requisito', r.id,
       concat_ws(E'\n',
           'REQUISITO: ' || r.titulo,
           r.descripcion,
           CASE WHEN r.aplica_si <> '{}'::jsonb
                THEN 'CONDICIÓN: ' || r.aplica_si::text END),
       jsonb_build_object('codigo', r.codigo, 'orden', r.orden),
       encode(digest(concat_ws('|', r.titulo, r.descripcion,
                                    r.aplica_si::text), 'sha256'), 'hex'),
       'pendiente'
FROM requisito_tramite r
JOIN tramite_version v ON v.id = r.tramite_version_id
WHERE v.estado_editorial = 'publicada';

INSERT INTO trabajo_embedding (fragmento_id, modelo)
SELECT id, 'text-embedding-004'
FROM fragmento_conocimiento
WHERE estado_embedding = 'pendiente';

-- Conversación sintética: no contiene PII y expira a los 30 días.
INSERT INTO sesion_anonima
    (identificador_hash, consentimiento_analytics, creada_en, expira_en)
VALUES
    (encode(digest('synthetic-test-session', 'sha256'), 'hex'), false,
     TIMESTAMPTZ '2026-07-25 12:00:00-04',
     TIMESTAMPTZ '2026-08-24 12:00:00-04');

INSERT INTO conversacion (sesion_id, titulo)
SELECT id, 'Consulta sintética de desarrollo'
FROM sesion_anonima
WHERE identificador_hash = encode(digest('synthetic-test-session', 'sha256'), 'hex');

INSERT INTO mensaje_conversacion (conversacion_id, rol, contenido)
SELECT id, 'usuario', '¿Dónde registro una empresa unipersonal?'
FROM conversacion
WHERE titulo = 'Consulta sintética de desarrollo';

-- -----------------------------------------------------------------------------
-- VALIDACIONES DE LA SEMILLA
-- Se usa una tabla temporal con CHECK en lugar de un bloque anónimo para evitar
-- que algunos editores web dividan incorrectamente sentencias largas.
-- -----------------------------------------------------------------------------
CREATE TEMP TABLE _validacion_seed (
    nombre  TEXT PRIMARY KEY,
    valido  BOOLEAN NOT NULL CHECK (valido)
) ON COMMIT DROP;

INSERT INTO _validacion_seed (nombre, valido)
SELECT 'tres_tramites_publicados', COUNT(*) = 3
FROM vw_tramite_publicado;

INSERT INTO _validacion_seed (nombre, valido)
SELECT 'publicaciones_con_fuente', COUNT(*) = 0
FROM tramite_version v
WHERE v.estado_editorial = 'publicada'
  AND NOT EXISTS (
      SELECT 1
      FROM tramite_version_fuente vf
      WHERE vf.tramite_version_id = v.id
  );

INSERT INTO _validacion_seed (nombre, valido)
SELECT 'sin_embeddings_falsos', COUNT(*) = 0
FROM fragmento_conocimiento
WHERE estado_embedding = 'listo'
  AND embedding IS NULL;

COMMIT;

-- Resumen visible al finalizar en psql o Neon SQL Editor.
SELECT 'instituciones' AS entidad, COUNT(*) AS registros FROM institucion
UNION ALL SELECT 'archivos_multimedia', COUNT(*) FROM archivo_multimedia
UNION ALL SELECT 'oficinas', COUNT(*) FROM oficina
UNION ALL SELECT 'tramites', COUNT(*) FROM tramite
UNION ALL SELECT 'versiones_publicadas', COUNT(*) FROM vw_tramite_publicado
UNION ALL SELECT 'requisitos', COUNT(*) FROM requisito_tramite
UNION ALL SELECT 'fuentes_oficiales', COUNT(*) FROM fuente_oficial
UNION ALL SELECT 'fragmentos_pendientes', COUNT(*) FROM fragmento_conocimiento
WHERE estado_embedding = 'pendiente';
